// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiygGSX2f4XGq3KIXhm4-g9HX7tx8vbt8',
    appId: '1:1064040890791:web:f74e6a42c5af11cac5f682',
    messagingSenderId: '1064040890791',
    projectId: 'moneymentor-7a192',
    authDomain: 'moneymentor-7a192.firebaseapp.com',
    storageBucket: 'moneymentor-7a192.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBB35DaQM8-saA4yXXR9SuThxQkQBZT63Y',
    appId: '1:1064040890791:android:d4013cbefa5128eec5f682',
    messagingSenderId: '1064040890791',
    projectId: 'moneymentor-7a192',
    storageBucket: 'moneymentor-7a192.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7rwEUiihQbABLRwq_NU2xckBNZDMb-Ms',
    appId: '1:391861641907:ios:48d782a2f01ea31dffc6c6',
    messagingSenderId: '391861641907',
    projectId: 'moneymentor02112',
    storageBucket: 'moneymentor02112.appspot.com',
    androidClientId: '391861641907-bob38a23ojuk8537qusi9f5ipt7srbo0.apps.googleusercontent.com',
    iosClientId: '391861641907-9con6vfmsih6qo75m1c2bbn4h80kslcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyMentor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7rwEUiihQbABLRwq_NU2xckBNZDMb-Ms',
    appId: '1:391861641907:ios:965dab7e15612448ffc6c6',
    messagingSenderId: '391861641907',
    projectId: 'moneymentor02112',
    storageBucket: 'moneymentor02112.appspot.com',
    androidClientId: '391861641907-bob38a23ojuk8537qusi9f5ipt7srbo0.apps.googleusercontent.com',
    iosClientId: '391861641907-sp5fpih3uik5vbto461rouepcvp4d0bs.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyMentor.RunnerTests',
  );
}